### ISSUE TITLE
If subdomain is not found, nav bar buttons will not work

### ISSUE THREAD

**Issue by cpbeaslin** [slmnio/slmngg-sfc#56]
**Describe the bug**
If subdomain is not found, nav bar buttons will not work

**To Reproduce**
go to subdomain that is not found
https://joeyisthecoolest.slmn.gg
Click any of the navbar buttons

**Expected behavior**
Navbar buttons bring you to a working page

If subdomain is not found, make navbar buttons redirect to slmn.gg/* without subdomain

**Comment by slmnio** [comment]
The 404s when clicking the navbar is expected behaviour - any subdomain will be part of an event, so event.slmn.gg/events will 404. 

The main thing is not finding a valid minisite from a subdomain uses the same 404 page. It should probably have something else  that explains a minisite hasn't been found and to go to slmn.gg or somewhere else.

**Comment by slmnio** [comment]
https://github.com/slmnio/slmngg-sfc/blob/8f6f4ebd91ba247d3988785e6b52910594de02ac/website/src/main.js#L90

New component can be added here

**Comment by slmnio** [comment]
Fixed in 2e9dc9579335ca376ab42ecad462a38c7104d974
